name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log directory contents
      run: ls -la

    - name: Log package.json
      run: cat package.json || echo "No package.json found"

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/offsyanka99/xbrowsersync:latest
          ghcr.io/offsyanka99/xbrowsersync:v1
        cache-from: type=gha
        cache-to: type=gha,mode=max
